### ISSUE TITLE
Yolov5 - deepstream and trition inference server

### ISSUE THREAD

**Issue by htran170642** [NVIDIA-AI-IOT/deepstream_triton_model_deploy#15]
Can we deploy Yolov5 using deepstream and trition?
Thanks.

**Comment by dsingal0** [comment]
Yes, please refer to: https://github.com/NVIDIA-AI-IOT/yolov4_deepstream

**Comment by ghost** [comment]
Since the YoloV5 repository https://github.com/ultralytics/yolov5/ provides a export to ONNX, you should be able to run it using Triton Inference Server under this DeepStream-app example. That said, you'll most probably have to write your own parser for the network output. 
Some references to help you get started:
The custom parser section from: https://developer.nvidia.com/blog/deploying-models-from-tensorflow-model-zoo-using-deepstream-and-triton-inference-server/
YOLOv5 to ONNX: https://github.com/ultralytics/yolov5/issues/251
^ this link also provides a way to turn the model into a TRT Engine, but YMMV for the Tensorrtx translation.
