### ISSUE TITLE
Face Alignment in Triton

### ISSUE THREAD

**Issue by akashmanna** [NVIDIA-AI-IOT/deepstream_triton_model_deploy#9]
Hi, Thanks for the amazing work!

It is mentioned in README of Centerface about performing Face Alignment using Triton [here](https://raw.githubusercontent.com/NVIDIA-AI-IOT/deepstream_triton_model_deploy/master/centerface/README.md)
```
 We are using Deepstream-5.0 with Triton Inference Server to deploy the Centerface network for face detection and alignment. 
```

But I could not find resources on Face Alignment in this repo.
Is a different custom parser being used for Face Alignment as well?

Additionally, How can the output crops after face alignment be obtained for further processing?

**Comment by ghost** [comment]
This project does not do face alignment. Please refer to the paper: https://arxiv.org/ftp/arxiv/papers/1911/1911.03599.pdf for more information on the face alignment. In order to implement face alignment you would modify the custom parser to use the `landmarks ` buffer output from the network. 
Since deepstream-app is an example for detection/segmentation/classification. In order to output the crops you could modify the code to deepstream-app to export the face crops using a custom plugin with openCV [Implementing a Custom GStreamer Plugin with OpenCV Integration Example
](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_sample_custom_gstream.html) or [crop and save locally](https://forums.developer.nvidia.com/t/how-to-crop-the-image-and-save/80174/24)
